<?php
/**
 * Barcode Setting toolbox columns — order/labels match common-modal-product-selection.php.
 *
 * @return list<array{field:string,label:string,search?:string}>
 */
function auragold_barcode_toolbox_columns(): array {
    return [
        ['field' => 'Id', 'label' => 'Id'],
        ['field' => 'RFIDCode', 'label' => 'RFIDCode'],
        ['field' => 'VoucherType', 'label' => 'Voucher Type'],
        ['field' => 'Barcode', 'label' => 'Barcode', 'search' => 'barcode barcode no barcodeno barcode number'],
        ['field' => 'DesignNo', 'label' => 'Design No'],
        ['field' => 'HUIDNo', 'label' => 'HUID No'],
        ['field' => 'ItemCode', 'label' => 'Item Code', 'search' => 'item code sku article'],
        ['field' => 'ShortCode', 'label' => 'Short Code', 'search' => 'short code shortcode supplier identity'],
        ['field' => 'Category', 'label' => 'Diamond Category', 'search' => 'diamond category diamonds gemstones jewellery'],
        ['field' => 'ProductCategory', 'label' => 'Category (Product)', 'search' => 'product category'],
        ['field' => 'Calculation', 'label' => 'Calculation'],
        ['field' => 'Product', 'label' => 'Product'],
        ['field' => 'Location', 'label' => 'Location'],
        ['field' => 'PktWt', 'label' => 'Pkt. Wt.'],
        ['field' => 'PktLessWt', 'label' => 'Pkt. Less Wt.'],
        ['field' => 'GrossWt', 'label' => 'Gross Wt.'],
        ['field' => 'StoneWeight', 'label' => 'Carat / Stone Wt.', 'search' => 'stone weight carat stone wt diamond carat'],
        ['field' => 'DiamondWt', 'label' => 'Diamond Wt.', 'search' => 'diamond wt diamond weight d weight less wt'],
        ['field' => 'TotalDiamond', 'label' => 'Total Diamond', 'search' => 'total diamond totaldiamond'],
        ['field' => 'TotalStones', 'label' => 'Total Stones', 'search' => 'total stones totalstones gemstone'],
        ['field' => 'LessWt', 'label' => 'Less Wt.'],
        ['field' => 'NetWt', 'label' => 'Net Wt.'],
        ['field' => 'Quantity', 'label' => 'Quantity'],
        ['field' => 'Rate', 'label' => 'Rate'],
        ['field' => 'FcAmount', 'label' => 'FC Amount'],
        ['field' => 'DiamondLineMetalValue', 'label' => 'Metal Value (line)'],
        ['field' => 'RapNetValuation', 'label' => 'RapNet Valuation'],
        ['field' => 'SettingCharge', 'label' => 'Setting Charge'],
        ['field' => 'StoneAmount', 'label' => 'Setting Charge Amt.'],
        ['field' => 'MarkUpAmount', 'label' => 'Mark Up Amt.'],
        ['field' => 'MarkUpPer', 'label' => 'Mark Up %'],
        ['field' => 'Amount', 'label' => 'Amount'],
        ['field' => 'MetalQty', 'label' => 'Metal Qty'],
        ['field' => 'MetalWeight', 'label' => 'Weight'],
        ['field' => 'Carat', 'label' => 'Karat', 'search' => 'karat carat 22k 18k 24k'],
        ['field' => 'Purity', 'label' => 'Purity'],
        ['field' => 'PurityWt', 'label' => 'Purity Wt'],
        ['field' => 'GoldLoss1', 'label' => 'Gold Loss 1'],
        ['field' => 'GoldLoss2', 'label' => 'Gold Loss 2'],
        ['field' => 'MetalLossValue', 'label' => 'Loss Value'],
        ['field' => 'WastagePer', 'label' => 'Wastage Per.'],
        ['field' => 'WastageWt', 'label' => 'Wastage Wt.'],
        ['field' => 'MetalRate', 'label' => 'Metal Rate'],
        ['field' => 'MetalValue', 'label' => 'Metal Value'],
        ['field' => 'PurchaseRate', 'label' => 'Purchase Rate'],
        ['field' => 'MetalCost', 'label' => 'Metal Cost'],
        ['field' => 'RequestedPurity', 'label' => 'Requested Purity'],
        ['field' => 'Requested', 'label' => 'Requested'],
        ['field' => 'FinalWt', 'label' => 'Final Wt.'],
        ['field' => 'AlloyWt', 'label' => 'Alloy Wt.'],
        ['field' => 'PlatinumWeight', 'label' => 'Pt. Wt.'],
        ['field' => 'PlatinumKarat', 'label' => 'Pt. Karat'],
        ['field' => 'PlatinumPurity', 'label' => 'Pt. Purity %'],
        ['field' => 'PlatinumPurityWt', 'label' => 'Pt. Purity Wt'],
        ['field' => 'PlatinumRate', 'label' => 'Pt. Rate'],
        ['field' => 'PlatinumWastagePer', 'label' => 'Pt. Wastg. %'],
        ['field' => 'PlatinumWastageWt', 'label' => 'Pt. Wastg. Wt'],
        ['field' => 'PlatinumAmount', 'label' => 'Pt. Amount'],
        ['field' => 'DiscountType', 'label' => 'Discount Type'],
        ['field' => 'DiscountPer', 'label' => 'Discount Per.'],
        ['field' => 'DiscountAmount', 'label' => 'Discount Amount'],
        ['field' => 'Discount', 'label' => 'Discount'],
        ['field' => 'MakingType', 'label' => 'Making Type'],
        ['field' => 'MakingRate', 'label' => 'Making Rate'],
        ['field' => 'MakingDiscountAmt', 'label' => 'Making Discount Amt.'],
        ['field' => 'MakingAmount', 'label' => 'Making Amount'],
        ['field' => 'MakingActualValue', 'label' => 'Making Actual Value'],
        ['field' => 'MakingCost', 'label' => 'Making Cost'],
        ['field' => 'MinimumPrice', 'label' => 'Minimum Price'],
        ['field' => 'MinimumCode', 'label' => 'Minimum Code'],
        ['field' => 'StoneChargeType', 'label' => 'Stone Charge Type'],
        ['field' => 'StoneRate', 'label' => 'Stone Rate'],
        ['field' => 'StoneCost', 'label' => 'Stone Cost'],
        ['field' => 'DiamondAmount', 'label' => 'Diamond Amount'],
        ['field' => 'PurchaseAmount', 'label' => 'Purchase Amount'],
        ['field' => 'SalePercent', 'label' => 'Sale Percentages'],
        ['field' => 'SaleAmount', 'label' => 'Sale Amount'],
        ['field' => 'SaleAmountWith', 'label' => 'Sale Amount With Tax'],
        ['field' => 'NetAmt', 'label' => 'Net Amt'],
        ['field' => 'TaxType', 'label' => 'Tax Type'],
        ['field' => 'TaxPer', 'label' => 'Tax %'],
        ['field' => 'Tax', 'label' => 'Tax'],
        ['field' => 'OtherChargeType', 'label' => 'Other Charge Type'],
        ['field' => 'OtherWeight', 'label' => 'Other Weight'],
        ['field' => 'OtherRate', 'label' => 'Other Rate'],
        ['field' => 'OtherInfo', 'label' => 'Other Info'],
        ['field' => 'OtherAmount', 'label' => 'Other Amount'],
        ['field' => 'CertificateAmount', 'label' => 'Certificate Amt.'],
        ['field' => 'CertificateNo', 'label' => 'Certificate No.'],
        ['field' => 'CertificateLink', 'label' => 'Certificate Link'],
        ['field' => 'VideoLink', 'label' => 'Video Link'],
        ['field' => 'Cut', 'label' => 'Cut'],
        ['field' => 'Color', 'label' => 'Color'],
        ['field' => 'SeiveSize', 'label' => 'Seive Size'],
        ['field' => 'Size', 'label' => 'Size'],
        ['field' => 'Shape', 'label' => 'Shape'],
        ['field' => 'Clarity', 'label' => 'Clarity'],
        ['field' => 'UnitPrice', 'label' => 'Unit Price'],
        ['field' => 'HallmarkAmount', 'label' => 'Hallmark Amount'],
        ['field' => 'HallmarkRate', 'label' => 'Hallmark Rate'],
        ['field' => 'NetAmtPlusTax', 'label' => 'Net Amt+Tax'],
        ['field' => 'Reverse', 'label' => 'Reverse'],
    ];
}
