<?php

/**
 * Menu / submenu structure aligned with admin/sidebar.php top navigation.
 * Optional per-page keys:
 * - grant_namespace: permission prefix module key when a page belongs under another module’s grants (e.g. Stock Transfer linked from Transaction mega menu uses inventory.*).
 * - group: mega-menu column / subsection title for display.
 */
function auragold_sidebar_permission_tree_data()
{
    $v = ['view'];
    $c = ['view', 'add', 'update', 'delete'];

    return [
        [
            'key'   => 'dashboards',
            'label' => 'Dashboards',
            'menu'  => true,
            'pages' => [
                ['key' => 'retailer', 'label' => 'Retailer', 'actions' => $v],
                ['key' => 'wholesaler', 'label' => 'Wholesaler', 'actions' => $v],
                ['key' => 'manufacturing', 'label' => 'Manufacturing / Job worker', 'actions' => $v],
                ['key' => 'sales_person', 'label' => 'Sales person', 'actions' => $v],
                ['key' => 'gold_rates', 'label' => 'Gold rates', 'actions' => $v],
                ['key' => 'stock_dash', 'label' => 'Stock', 'actions' => $v],
            ],
        ],
        [
            'key'   => 'utilities',
            'label' => 'Opening',
            'menu'  => true,
            'pages' => [
                ['key' => 'product_opening', 'label' => 'Product Opening', 'actions' => $c],
                ['key' => 'account_ledger', 'label' => 'Account Ledger', 'actions' => $c],
                ['key' => 'customer_details_import', 'label' => 'Customer Details Import', 'actions' => $c],
                ['key' => 'metal_to_amount', 'label' => 'Metal to Amount', 'actions' => $c],
                ['key' => 'amount_to_metal', 'label' => 'Amount to Metal', 'actions' => $c],
                ['key' => 'parties', 'label' => 'Parties', 'actions' => $c],
                ['key' => 'appraisal', 'label' => 'Appraisal', 'actions' => $c],
                ['key' => 'bank_reconciliation', 'label' => 'Bank Reconciliation', 'actions' => $c],
                ['key' => 'ewaybill_api_settings', 'label' => 'e-Way Bill API settings', 'group' => 'GST / e-Way Bill API', 'actions' => $c],
                ['key' => 'ewaybill_authentication', 'label' => 'e-Way Bill authentication', 'group' => 'GST / e-Way Bill API', 'actions' => $c],
            ],
        ],
        [
            'key'   => 'transaction',
            'label' => 'Operations',
            'menu'  => true,
            'pages' => [
                ['key' => 'sale_invoice', 'label' => 'Sales Invoice', 'group' => 'Sales & Purchase', 'actions' => $c],
                ['key' => 'sale_quotation', 'label' => 'Sales enquiry', 'group' => 'Sales & Purchase', 'actions' => $c],
                ['key' => 'sale_return', 'label' => 'Sales Return', 'group' => 'Sales & Purchase', 'actions' => $c],
                ['key' => 'purchase_invoice', 'label' => 'Purchase Invoice', 'group' => 'Sales & Purchase', 'actions' => $c],
                ['key' => 'purchase_quotation', 'label' => 'Purchase Inquiry', 'group' => 'Sales & Purchase', 'actions' => $c],
                ['key' => 'purchase_return', 'label' => 'Purchase Return', 'group' => 'Sales & Purchase', 'actions' => $c],
                ['key' => 'payment_voucher', 'label' => 'Payment Voucher', 'group' => 'Payments & Receipts', 'actions' => $c],
                ['key' => 'receipt_voucher', 'label' => 'Receipt Voucher', 'group' => 'Payments & Receipts', 'actions' => $c],
                ['key' => 'advance_payment', 'label' => 'Advance Voucher', 'group' => 'Payments & Receipts', 'actions' => $c],
                ['key' => 'cheque_entry', 'label' => 'Cheque Entry', 'group' => 'Payments & Receipts', 'actions' => $c],
                ['key' => 'stock_transfer', 'label' => 'Branch Transfer', 'group' => 'Material Management', 'grant_namespace' => 'inventory', 'actions' => $c],
                ['key' => 'material_issue', 'label' => 'Metal Issue', 'group' => 'Material Management', 'actions' => $c],
                ['key' => 'material_receive', 'label' => 'Metal Receive', 'group' => 'Material Management', 'actions' => $c],
                ['key' => 'stock_transfer_history', 'label' => 'Transfer History', 'group' => 'Material Management', 'grant_namespace' => 'inventory', 'actions' => $v],
                ['key' => 'stock_receive_history', 'label' => 'Receive History', 'group' => 'Material Management', 'grant_namespace' => 'inventory', 'actions' => $v],
                ['key' => 'old_jewelry_scrap_invoice', 'label' => 'Scrap Purchase Invoice', 'group' => 'Material Management', 'actions' => $c],
                ['key' => 'old_jewellery_scrap', 'label' => 'Scrap Stock', 'group' => 'Material Management', 'actions' => $c],
                ['key' => 'stock_journal', 'label' => 'Stock Journal', 'group' => 'Accounting & Journals', 'actions' => $c],
                ['key' => 'credit_note', 'label' => 'Credit Note', 'group' => 'Accounting & Journals', 'actions' => $c],
                ['key' => 'debit_note', 'label' => 'Debit Note', 'group' => 'Accounting & Journals', 'actions' => $c],
                ['key' => 'contra_voucher', 'label' => 'Contra Voucher', 'group' => 'Accounting & Journals', 'actions' => $c],
                ['key' => 'journal_voucher', 'label' => 'Journal Voucher', 'group' => 'Accounting & Journals', 'actions' => $c],
                ['key' => 'expense_invoice', 'label' => 'Expense Invoice', 'group' => 'Accounting & Journals', 'actions' => $c],
                ['key' => 'repair_invoice', 'label' => 'Jewellery Repair Invoice', 'group' => 'Accounting & Journals', 'actions' => $c],
                ['key' => 'investment_fund', 'label' => 'Saving Scheme / Layaway Fund', 'group' => 'Accounting & Journals', 'actions' => $c],
                ['key' => 'installment_report', 'label' => 'EMI & Saving Scheme Report', 'group' => 'Accounting & Journals', 'actions' => $v],
            ],
        ],
        [
            'key'   => 'inventory',
            'label' => 'Stock Management',
            'menu'  => true,
            'pages' => [
                ['key' => 'jewellery_catalogue', 'label' => 'Product Catalogue', 'group' => 'Catalogue & Stock', 'actions' => $c],
                ['key' => 'physical_stock', 'label' => 'Barcode Re-Print', 'group' => 'Catalogue & Stock', 'actions' => $c],
                ['key' => 'memo_consignment_in', 'label' => 'Memo In', 'group' => 'Consignment & Transfer', 'actions' => $c],
                ['key' => 'memo_consignment_out', 'label' => 'Memo Out', 'group' => 'Consignment & Transfer', 'actions' => $c],
                ['key' => 'memo_consignment_items', 'label' => 'Memo Inventory', 'group' => 'Consignment & Transfer', 'actions' => $c],
                ['key' => 'stock_history', 'label' => 'Stock History', 'group' => 'Consignment & Transfer', 'actions' => $v],
                ['key' => 'stock_transfer', 'label' => 'Branch Transfer', 'group' => 'Consignment & Transfer', 'actions' => $c],
                ['key' => 'stock_transfer_history', 'label' => 'Transfer History', 'group' => 'Consignment & Transfer', 'actions' => $v],
                ['key' => 'stock_receive_history', 'label' => 'Receive History', 'group' => 'Consignment & Transfer', 'actions' => $v],
                ['key' => 'gold_silver', 'label' => 'Gold & Silver', 'group' => 'Gold, Platinum & Diamond', 'actions' => $c],
                ['key' => 'gold_silver_analysis', 'label' => 'Gold & Silver Inventory', 'group' => 'Gold, Platinum & Diamond', 'actions' => $c],
                ['key' => 'platinum', 'label' => 'Platinum', 'group' => 'Gold, Platinum & Diamond', 'actions' => $c],
                ['key' => 'platinum_analysis', 'label' => 'Platinum', 'group' => 'Gold, Platinum & Diamond', 'actions' => $c],
                ['key' => 'diamond_stone', 'label' => 'Diamond & Stone Inventory', 'group' => 'Gold, Platinum & Diamond', 'actions' => $c],
                ['key' => 'diamond_stone_analysis', 'label' => 'Diamond & Stone', 'group' => 'Gold, Platinum & Diamond', 'actions' => $c],
                ['key' => 'imitation_watches', 'label' => 'Imitation / Watches', 'group' => 'Imitation, Services & Reports', 'actions' => $c],
                ['key' => 'imitation_watches_analysis', 'label' => 'Imitation / Watches Inventory', 'group' => 'Imitation, Services & Reports', 'actions' => $c],
                ['key' => 'other_services', 'label' => 'Service Management', 'group' => 'Imitation, Services & Reports', 'actions' => $c],
                ['key' => 'other_services_analysis', 'label' => 'Service Analytics', 'group' => 'Imitation, Services & Reports', 'actions' => $v],
                ['key' => 'rfid_barcode_scan', 'label' => 'RFID & Barcode Scanner', 'group' => 'Imitation, Services & Reports', 'actions' => $c],
                ['key' => 'reset_rfid_tag', 'label' => 'RFID Tag Management', 'group' => 'Imitation, Services & Reports', 'actions' => $c],
                ['key' => 'barcode', 'label' => 'Barcode Management', 'group' => 'Imitation, Services & Reports', 'actions' => $c],
                ['key' => 'stock_valuation', 'label' => 'Inventory Valuation', 'group' => 'Imitation, Services & Reports', 'actions' => $v],
                ['key' => 'stock_summary_report', 'label' => 'Inventory Summary', 'group' => 'Imitation, Services & Reports', 'actions' => $v],
                ['key' => 'carat_analysis_report', 'label' => 'Purity & Carat Analysis', 'group' => 'Imitation, Services & Reports', 'actions' => $v],
                ['key' => 'procurement_operations', 'label' => 'Procurement Management', 'group' => 'Imitation, Services & Reports', 'actions' => $c],
            ],
        ],
        [
            'key'   => 'orders',
            'label' => 'Order Management',
            'menu'  => true,
            'pages' => [
                ['key' => 'sale_order', 'label' => 'Sale Order', 'actions' => $c],
                ['key' => 'repair_order', 'label' => 'Repair Order', 'actions' => $c],
                ['key' => 'sale_repair_order_process', 'label' => 'Order & Repair Processing', 'actions' => $c],
                ['key' => 'repair_order_process', 'label' => 'Repair Order Process', 'actions' => $c],
                ['key' => 'jobwork_order_manufacturing', 'label' => 'Manufacturing Work Order', 'actions' => $c],
                ['key' => 'jobwork_order_outsource', 'label' => 'Outsourced Job Work', 'actions' => $c],
                ['key' => 'purchase_order', 'label' => 'Purchase Order', 'actions' => $c],
                ['key' => 'jobwork_order_print', 'label' => 'Jobwork Order Print', 'actions' => $v],
                ['key' => 'catalogue_quotation', 'label' => 'Design Quotation', 'actions' => $c],
                ['key' => 'sales', 'label' => 'Sales Register', 'actions' => $c],
            ],
        ],
        [
            'key'   => 'manufacturer',
            'label' => 'Production',
            'menu'  => true,
            'pages' => [
                ['key' => 'department', 'label' => 'Department', 'actions' => $c],
                ['key' => 'department_report', 'label' => 'Insource Department Report', 'actions' => $v],
                ['key' => 'outsource_department_report', 'label' => 'Outsource Department Report', 'actions' => $v],
                ['key' => 'jobwork_queue', 'label' => 'Jobwork Queue', 'actions' => $c],
                ['key' => 'manufacturing_process', 'label' => 'Manufacturing Process', 'actions' => $c],
                ['key' => 'jobwork_queue_report', 'label' => 'Jobwork Queue Report', 'actions' => $v],
                ['key' => 'loss_tracking', 'label' => 'Loss Tracking', 'actions' => $v],
                ['key' => 'closing_report', 'label' => 'Closing Report', 'actions' => $v],
                ['key' => 'worklog_report', 'label' => 'Worklog Report', 'actions' => $v],
                ['key' => 'jobcard_report', 'label' => 'Jobcard Report', 'actions' => $v],
                ['key' => 'jobcard_print', 'label' => 'Jobcard Print', 'actions' => $v],
                ['key' => 'daily_manufacturing_summary', 'label' => 'Daily Manufacturing Summary', 'actions' => $v],
            ],
        ],
        [
            'key'   => 'financial_statement',
            'label' => 'Financial Statement',
            'menu'  => true,
            'pages' => [
                ['key' => 'trial_balance', 'label' => 'Trial Balance', 'actions' => $v],
                ['key' => 'balance_sheet', 'label' => 'Balance Sheet', 'actions' => $v],
                ['key' => 'profit_loss', 'label' => 'Profit Loss', 'actions' => $v],
                ['key' => 'cash_flow', 'label' => 'Cash Flow', 'actions' => $v],
                ['key' => 'fund_flow', 'label' => 'Fund Flow', 'actions' => $v],
                ['key' => 'chart_of_account', 'label' => 'Chart Of Account', 'actions' => $c],
                ['key' => 'tax_return', 'label' => 'Tax Return', 'actions' => $v],
                ['key' => 'sale_analysis', 'label' => 'Sale Reports', 'actions' => $v],
                ['key' => 'purchase_financial_analysis', 'label' => 'Purchase Reports', 'actions' => $v],
                ['key' => 'trial_balance_detailed_report', 'label' => 'Trial Balance Detailed Report', 'actions' => $v],
            ],
        ],
        [
            'key'   => 'report',
            'label' => 'Report Analysis',
            'menu'  => true,
            'pages' => [
                ['key' => 'transaction_report', 'label' => 'Transactions Report', 'actions' => $v],
                ['key' => 'account_ledger_report', 'label' => 'Account Ledger Report', 'actions' => $v],
                ['key' => 'day_report', 'label' => 'Day Report', 'actions' => $v],
                ['key' => 'ageing_report', 'label' => 'Ageing Report', 'actions' => $v],
                ['key' => 'daily_sales_collection_summary', 'label' => 'Daily Sales And Collection Summary', 'actions' => $v],
                ['key' => 'borrowers_report', 'label' => 'Borrowers Report', 'actions' => $v],
                ['key' => 'customer_kyc_report', 'label' => 'Customer / KYC Report', 'actions' => $v],
                ['key' => 'ledger_balance_report', 'label' => 'Ledger Balance Report', 'actions' => $v],
                ['key' => 'fixing_position', 'label' => 'Fixing Position', 'actions' => $v],
                ['key' => 'karatwise_profit_loss', 'label' => 'Karatwise Profit & Loss', 'actions' => $v],
                ['key' => 'reward_point_report', 'label' => 'Reward Point Report', 'actions' => $v],
                ['key' => 'barcode_scan_report', 'label' => 'Barcode Scan Report', 'actions' => $v],
            ],
        ],
        [
            'key'   => 'gst_report',
            'label' => 'GST Reports',
            'menu'  => true,
            'pages' => [
                ['key' => 'gst_reports_hub', 'label' => 'GST Reports Hub', 'actions' => $v],
                ['key' => 'gstr1', 'label' => 'GSTR-1', 'actions' => $v],
                ['key' => 'gstr3b', 'label' => 'GSTR-3B', 'actions' => $v],
                ['key' => 'gstr2b', 'label' => 'GSTR-2B Reconciliation', 'actions' => $v],
                ['key' => 'gstr9', 'label' => 'GSTR-9', 'actions' => $v],
            ],
        ],
        [
            'key'   => 'employee_management',
            'label' => 'Employee Management',
            'menu'  => true,
            'pages' => [
                ['key' => 'employee_dashboard', 'label' => 'Employee Dashboard', 'actions' => $v],
                ['key' => 'employee_attendance', 'label' => 'Employee Attendance', 'actions' => $c],
                ['key' => 'employee_attendance_report', 'label' => 'Attendance Report', 'actions' => $v],
                ['key' => 'employee_advance', 'label' => 'Employee Advance', 'actions' => $c],
                ['key' => 'employee_advance_request', 'label' => 'Advance Request', 'actions' => $c],
                ['key' => 'employee_incentive', 'label' => 'Employee Incentive', 'actions' => $c],
                ['key' => 'expense_category', 'label' => 'Expense Category', 'actions' => $c],
                ['key' => 'expenses', 'label' => 'Expenses', 'actions' => $c],
                ['key' => 'employee_reports', 'label' => 'Employee Reports', 'actions' => $v],
                ['key' => 'employee_salary', 'label' => 'Employee Salary', 'actions' => $c],
                ['key' => 'assign_inventory_sales_team', 'label' => 'Assign Inventory To Sales Team', 'actions' => $v],
                ['key' => 'assign_inventory', 'label' => 'Assign Inventory', 'actions' => $c],
                ['key' => 'unassign_inventory', 'label' => 'UnAssign Inventory', 'actions' => $c],
                ['key' => 'assign_inventory_items', 'label' => 'Assign Inventory Items', 'actions' => $c],
            ],
        ],
        [
            'key'   => 'settings',
            'label' => 'Settings',
            'menu'  => true,
            'pages' => [
                ['key' => 'set_software', 'label' => 'Set Software', 'actions' => $c],
                ['key' => 'voucher_type', 'label' => 'Voucher Type', 'actions' => $c],
                ['key' => 'invoice_print_settings', 'label' => 'Invoice print settings', 'actions' => $c],
                ['key' => 'user_management', 'label' => 'User Management', 'group' => 'Administration', 'grant_namespace' => 'administration', 'actions' => $c],
                ['key' => 'masters', 'label' => 'Masters', 'group' => 'Administration', 'grant_namespace' => 'administration', 'actions' => $c],
                ['key' => 'activity_log', 'label' => 'Activity Log', 'group' => 'Administration', 'grant_namespace' => 'administration', 'actions' => $v],
                ['key' => 'crm', 'label' => 'CRM', 'group' => 'Administration', 'grant_namespace' => 'administration', 'actions' => $c],
                ['key' => 'role_management', 'label' => 'Role Management', 'group' => 'Administration', 'grant_namespace' => 'administration', 'actions' => $c],
                ['key' => 'permission_management', 'label' => 'Permission Management', 'group' => 'Administration', 'grant_namespace' => 'administration', 'actions' => $c],
                ['key' => 'whitelist_management', 'label' => 'Whitelist Management', 'group' => 'Administration', 'grant_namespace' => 'administration', 'actions' => $c],
                ['key' => 'blocklist_management', 'label' => 'Blocklist Management', 'group' => 'Administration', 'grant_namespace' => 'administration', 'actions' => $c],
            ],
        ],
    ];
}
