-- Post-dated cheque (PDC) entries
CREATE TABLE IF NOT EXISTS `tbl_cheque_entry` (
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `branch_id` int DEFAULT NULL COMMENT 'FK tbl_branches.id',
    `pdc_no` varchar(50) NOT NULL DEFAULT '',
    `account_no` varchar(100) NOT NULL DEFAULT '',
    `account_ledger` varchar(255) NOT NULL DEFAULT '',
    `bank_name` varchar(255) NOT NULL DEFAULT '',
    `cheque_no` varchar(100) NOT NULL DEFAULT '',
    `cheque_date` date DEFAULT NULL,
    `pay_date` date DEFAULT NULL,
    `amount` decimal(14,2) NOT NULL DEFAULT 0.00,
    `branch_name` varchar(255) NOT NULL DEFAULT '',
    `status` varchar(50) NOT NULL DEFAULT 'Pending',
    `bounced_cleared_date` date DEFAULT NULL,
    `against_voucher_no` varchar(100) NOT NULL DEFAULT '',
    `against_voucher_type` varchar(100) NOT NULL DEFAULT '',
    `nsf_fees` decimal(14,2) NOT NULL DEFAULT 0.00,
    `recoverable` tinyint(1) NOT NULL DEFAULT 0,
    `invoice_date` date DEFAULT NULL,
    `reference_voucher_type` varchar(100) NOT NULL DEFAULT '',
    `ref_invoice_no` varchar(100) NOT NULL DEFAULT '',
    `comment` text,
    `pdc_voucher_type` varchar(100) NOT NULL DEFAULT '',
    `record_status` tinyint(1) NOT NULL DEFAULT 1,
    `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
    `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_cheque_entry_branch` (`branch_id`),
    KEY `idx_cheque_entry_pdc_no` (`pdc_no`),
    KEY `idx_cheque_entry_status` (`status`),
    KEY `idx_cheque_entry_record_status` (`record_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
