-- Create Purchase Quotation Tables
-- Run this SQL script to create the necessary tables for purchase quotations

-- Table: tbl_purchase_quotations
CREATE TABLE IF NOT EXISTS `tbl_purchase_quotations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quotation_no` varchar(50) NOT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  `supplier_name` varchar(255) NOT NULL,
  `against_of` varchar(100) DEFAULT NULL,
  `currency` varchar(10) DEFAULT 'USD',
  `rate` decimal(15,6) DEFAULT 1.000000,
  `ref_no` varchar(100) DEFAULT NULL,
  `purchase_person` varchar(255) DEFAULT NULL,
  `quotation_date` date NOT NULL,
  `due_date` date DEFAULT NULL,
  `layaways_id` int(11) DEFAULT NULL,
  `fixing_type` varchar(50) DEFAULT 'Standard',
  `ounce_rate` decimal(15,2) DEFAULT 0.00,
  `unfix_dmd_gms` tinyint(1) DEFAULT 0,
  `unfix_metal` tinyint(1) DEFAULT 0,
  `unfix` tinyint(1) DEFAULT 0,
  `previous_balance` decimal(15,2) DEFAULT 0.00,
  `previous_gold` decimal(15,2) DEFAULT 0.00,
  `previous_silver` decimal(15,2) DEFAULT 0.00,
  `subtotal` decimal(15,2) DEFAULT 0.00,
  `additional_amt` decimal(15,2) DEFAULT 0.00,
  `net_total` decimal(15,2) DEFAULT 0.00,
  `discount_amt` decimal(15,2) DEFAULT 0.00,
  `grand_total` decimal(15,2) DEFAULT 0.00,
  `advance_payment` decimal(15,2) DEFAULT 0.00,
  `metal_amt` decimal(15,2) DEFAULT 0.00,
  `round_off` decimal(15,2) DEFAULT 0.00,
  `return_invoice` decimal(15,2) DEFAULT 0.00,
  `paid_amt` decimal(15,2) DEFAULT 0.00,
  `balance_amt` decimal(15,2) DEFAULT 0.00,
  `group_name` varchar(255) DEFAULT NULL,
  `comment` text DEFAULT NULL,
  `status` varchar(20) DEFAULT 'draft',
  `created_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `quotation_no` (`quotation_no`),
  KEY `supplier_id` (`supplier_id`),
  KEY `quotation_date` (`quotation_date`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: tbl_purchase_quotation_items
CREATE TABLE IF NOT EXISTS `tbl_purchase_quotation_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quotation_id` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_characteristic_id` int(11) DEFAULT NULL,
  `barcode` varchar(100) DEFAULT NULL,
  `product_name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `carat` varchar(50) DEFAULT NULL,
  `quantity` decimal(10,2) DEFAULT 1.00,
  `gross_weight` decimal(10,3) DEFAULT 0.000,
  `final_weight` decimal(10,3) DEFAULT 0.000,
  `net_weight` decimal(10,3) DEFAULT 0.000,
  `pure_weight` decimal(10,3) DEFAULT 0.000,
  `making_amount` decimal(15,2) DEFAULT 0.00,
  `tax_amount` decimal(15,2) DEFAULT 0.00,
  `amount` decimal(15,2) DEFAULT 0.00,
  `net_amount` decimal(15,2) DEFAULT 0.00,
  `net_amt_weight` decimal(15,2) DEFAULT 0.00,
  `diamond_weight` decimal(10,3) DEFAULT 0.000,
  `gemstone_weight` decimal(10,3) DEFAULT 0.000,
  `diamond_amount` decimal(15,2) DEFAULT 0.00,
  `design_no` varchar(100) DEFAULT NULL,
  `status` tinyint(1) DEFAULT 1,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `quotation_id` (`quotation_id`),
  KEY `product_id` (`product_id`),
  KEY `product_characteristic_id` (`product_characteristic_id`),
  KEY `barcode` (`barcode`),
  CONSTRAINT `fk_purchase_quotation_items_quotation` FOREIGN KEY (`quotation_id`) REFERENCES `tbl_purchase_quotations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: tbl_purchase_quotation_payments
CREATE TABLE IF NOT EXISTS `tbl_purchase_quotation_payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quotation_id` int(11) NOT NULL,
  `payment_type` varchar(50) NOT NULL,
  `diamond_category` varchar(100) DEFAULT NULL,
  `transaction_no` varchar(100) DEFAULT NULL,
  `transfer_from` varchar(100) DEFAULT NULL,
  `deposit_into` varchar(100) DEFAULT NULL,
  `product` varchar(255) DEFAULT NULL,
  `cheque_date` date DEFAULT NULL,
  `weight` decimal(10,3) DEFAULT 0.000,
  `metal` varchar(100) DEFAULT NULL,
  `quantity` decimal(10,2) DEFAULT 0.00,
  `purity_carat` varchar(50) DEFAULT NULL,
  `amount` decimal(15,2) NOT NULL,
  `status` tinyint(1) DEFAULT 1,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `quotation_id` (`quotation_id`),
  CONSTRAINT `fk_purchase_quotation_payments_quotation` FOREIGN KEY (`quotation_id`) REFERENCES `tbl_purchase_quotations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
