-- Create Consignment Out Tables
-- Run this SQL script to create the necessary tables for Consignment Out (Stock Out) management

-- Table: tbl_consignment_out (Master table)
CREATE TABLE IF NOT EXISTS `tbl_consignment_out` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `consignment_no` varchar(50) NOT NULL COMMENT 'CO-1, CO-2, etc.',
  `customer_id` int(11) DEFAULT NULL,
  `customer_name` varchar(255) NOT NULL,
  `consignment_date` date NOT NULL,
  `ref_no` varchar(100) DEFAULT NULL,
  `against_of` varchar(100) DEFAULT NULL,
  `currency` varchar(10) DEFAULT 'AED',
  `fixing_type` varchar(50) DEFAULT 'Standard',
  `sales_person` varchar(255) DEFAULT NULL,
  `previous_balance` decimal(15,2) DEFAULT 0.00,
  `previous_gold` decimal(10,3) DEFAULT 0.000,
  `previous_silver` decimal(10,3) DEFAULT 0.000,
  `gross_total` decimal(15,2) DEFAULT 0.00,
  `discount_amount` decimal(15,2) DEFAULT 0.00,
  `tax_amount` decimal(15,2) DEFAULT 0.00,
  `grand_total` decimal(15,2) DEFAULT 0.00,
  `total_quantity` int(11) DEFAULT 0,
  `total_gross_weight` decimal(10,3) DEFAULT 0.000,
  `total_net_weight` decimal(10,3) DEFAULT 0.000,
  `total_pure_weight` decimal(10,3) DEFAULT 0.000,
  `comment` text DEFAULT NULL,
  `status` varchar(20) DEFAULT 'active' COMMENT 'active, cancelled, returned',
  `created_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `consignment_no` (`consignment_no`),
  KEY `customer_id` (`customer_id`),
  KEY `customer_name` (`customer_name`),
  KEY `consignment_date` (`consignment_date`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: tbl_consignment_out_items (Items/Products table)
CREATE TABLE IF NOT EXISTS `tbl_consignment_out_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `consignment_id` int(11) NOT NULL,
  `product_id` int(11) DEFAULT NULL,
  `product_characteristic_id` int(11) DEFAULT NULL,
  `barcode` varchar(100) DEFAULT NULL,
  `product_name` varchar(255) DEFAULT NULL,
  `design_no` varchar(100) DEFAULT NULL,
  `huid_no` varchar(100) DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `calculation_mode` varchar(50) DEFAULT NULL,
  `location` varchar(100) DEFAULT NULL,
  `metal_id` int(11) DEFAULT NULL,
  `carat` varchar(50) DEFAULT NULL,
  `quantity` int(11) DEFAULT 1,
  `gross_weight` decimal(10,3) DEFAULT 0.000,
  `less_weight` decimal(10,3) DEFAULT 0.000,
  `net_weight` decimal(10,3) DEFAULT 0.000,
  `purity` decimal(10,4) DEFAULT 0.0000,
  `purity_weight` decimal(10,3) DEFAULT 0.000,
  `wastage_percent` decimal(10,2) DEFAULT 0.00,
  `wastage_weight` decimal(10,3) DEFAULT 0.000,
  `final_weight` decimal(10,3) DEFAULT 0.000,
  `pure_weight` decimal(10,3) DEFAULT 0.000,
  `rate` decimal(15,2) DEFAULT 0.00,
  `metal_value` decimal(15,2) DEFAULT 0.00,
  `amount` decimal(15,2) DEFAULT 0.00,
  `making_type` varchar(50) DEFAULT NULL,
  `making_rate` decimal(15,2) DEFAULT 0.00,
  `making_amount` decimal(15,2) DEFAULT 0.00,
  `stone_weight` decimal(10,3) DEFAULT 0.000,
  `stone_rate` decimal(15,2) DEFAULT 0.00,
  `stone_amount` decimal(15,2) DEFAULT 0.00,
  `diamond_amount` decimal(15,2) DEFAULT 0.00,
  `other_amount` decimal(15,2) DEFAULT 0.00,
  `discount_percent` decimal(10,2) DEFAULT 0.00,
  `discount_amount` decimal(15,2) DEFAULT 0.00,
  `tax_percent` decimal(10,2) DEFAULT 0.00,
  `tax_amount` decimal(15,2) DEFAULT 0.00,
  `net_amount` decimal(15,2) DEFAULT 0.00,
  `net_amt_with_tax` decimal(15,2) DEFAULT 0.00,
  `status` tinyint(1) DEFAULT 1,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `consignment_id` (`consignment_id`),
  KEY `product_id` (`product_id`),
  KEY `barcode` (`barcode`),
  KEY `product_characteristic_id` (`product_characteristic_id`),
  CONSTRAINT `fk_consignment_out_items_consignment` FOREIGN KEY (`consignment_id`) REFERENCES `tbl_consignment_out` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
