-- Consignment In Tables for AuraGold
-- Run this script in your MySQL database (auragold)

-- Master table for Consignment In
CREATE TABLE IF NOT EXISTS `tbl_consignment_in` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `consignment_no` VARCHAR(50) NOT NULL COMMENT 'Format: CI-1, CI-2, etc.',
    `consignment_out_id` INT(11) DEFAULT NULL COMMENT 'Reference to original consignment out if applicable',
    `customer_id` INT(11) DEFAULT NULL,
    `customer_name` VARCHAR(255) DEFAULT NULL,
    `consignment_date` DATE DEFAULT NULL,
    `ref_no` VARCHAR(100) DEFAULT NULL,
    `against_of` VARCHAR(255) DEFAULT NULL,
    `currency` VARCHAR(10) DEFAULT 'AED',
    `fixing_type` VARCHAR(50) DEFAULT 'Standard',
    `sales_person` VARCHAR(255) DEFAULT NULL,
    `previous_balance` DECIMAL(15,2) DEFAULT 0.00,
    `previous_gold` DECIMAL(15,3) DEFAULT 0.000,
    `previous_silver` DECIMAL(15,3) DEFAULT 0.000,
    `gross_total` DECIMAL(15,2) DEFAULT 0.00,
    `discount_amount` DECIMAL(15,2) DEFAULT 0.00,
    `tax_amount` DECIMAL(15,2) DEFAULT 0.00,
    `grand_total` DECIMAL(15,2) DEFAULT 0.00,
    `total_quantity` INT(11) DEFAULT 0,
    `total_gross_weight` DECIMAL(15,3) DEFAULT 0.000,
    `total_net_weight` DECIMAL(15,3) DEFAULT 0.000,
    `total_pure_weight` DECIMAL(15,3) DEFAULT 0.000,
    `comment` TEXT DEFAULT NULL,
    `status` VARCHAR(20) DEFAULT 'active' COMMENT 'active, cancelled, completed',
    `created_by` INT(11) DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `consignment_no` (`consignment_no`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_consignment_date` (`consignment_date`),
    KEY `idx_status` (`status`),
    KEY `idx_consignment_out_id` (`consignment_out_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Items table for Consignment In
CREATE TABLE IF NOT EXISTS `tbl_consignment_in_items` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `consignment_id` INT(11) NOT NULL,
    `product_id` INT(11) DEFAULT NULL,
    `product_characteristic_id` INT(11) DEFAULT NULL,
    `barcode` VARCHAR(100) DEFAULT NULL,
    `product_name` VARCHAR(255) DEFAULT NULL,
    `design_no` VARCHAR(100) DEFAULT NULL,
    `huid_no` VARCHAR(100) DEFAULT NULL,
    `category` VARCHAR(100) DEFAULT NULL,
    `calculation_mode` VARCHAR(50) DEFAULT NULL,
    `location` VARCHAR(100) DEFAULT NULL,
    `metal_id` INT(11) DEFAULT NULL,
    `carat` VARCHAR(20) DEFAULT NULL,
    `quantity` INT(11) DEFAULT 1,
    `gross_weight` DECIMAL(15,3) DEFAULT 0.000,
    `less_weight` DECIMAL(15,3) DEFAULT 0.000,
    `net_weight` DECIMAL(15,3) DEFAULT 0.000,
    `purity` DECIMAL(10,4) DEFAULT 0.0000,
    `purity_weight` DECIMAL(15,3) DEFAULT 0.000,
    `wastage_percent` DECIMAL(10,2) DEFAULT 0.00,
    `wastage_weight` DECIMAL(15,3) DEFAULT 0.000,
    `final_weight` DECIMAL(15,3) DEFAULT 0.000,
    `pure_weight` DECIMAL(15,3) DEFAULT 0.000,
    `rate` DECIMAL(15,2) DEFAULT 0.00,
    `metal_value` DECIMAL(15,2) DEFAULT 0.00,
    `amount` DECIMAL(15,2) DEFAULT 0.00,
    `making_type` VARCHAR(50) DEFAULT NULL,
    `making_rate` DECIMAL(15,2) DEFAULT 0.00,
    `making_amount` DECIMAL(15,2) DEFAULT 0.00,
    `stone_weight` DECIMAL(15,3) DEFAULT 0.000,
    `stone_rate` DECIMAL(15,2) DEFAULT 0.00,
    `stone_amount` DECIMAL(15,2) DEFAULT 0.00,
    `diamond_amount` DECIMAL(15,2) DEFAULT 0.00,
    `other_amount` DECIMAL(15,2) DEFAULT 0.00,
    `discount_percent` DECIMAL(10,2) DEFAULT 0.00,
    `discount_amount` DECIMAL(15,2) DEFAULT 0.00,
    `tax_percent` DECIMAL(10,2) DEFAULT 0.00,
    `tax_amount` DECIMAL(15,2) DEFAULT 0.00,
    `net_amount` DECIMAL(15,2) DEFAULT 0.00,
    `net_amt_with_tax` DECIMAL(15,2) DEFAULT 0.00,
    `status` TINYINT(1) DEFAULT 1,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_consignment_id` (`consignment_id`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_barcode` (`barcode`),
    CONSTRAINT `fk_consignment_in_items_master` FOREIGN KEY (`consignment_id`) REFERENCES `tbl_consignment_in` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Add index to stock journal if not exists for consignment_in type
-- This ensures efficient querying of stock movements
ALTER TABLE `tbl_stock_journal` ADD INDEX IF NOT EXISTS `idx_transaction_type` (`transaction_type`);
