-- Create table for Sale Fixing Direct Invoice
CREATE TABLE IF NOT EXISTS `tbl_sale_fixing_direct` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_no` varchar(50) NOT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `customer_name` varchar(255) NOT NULL,
  `ref_no` varchar(100) DEFAULT NULL,
  `sales_person` varchar(255) DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `layaways_id` int(11) DEFAULT NULL,
  `layaways` tinyint(1) DEFAULT '0',
  `against` varchar(100) DEFAULT NULL,
  `against_of` varchar(255) DEFAULT NULL,
  `currency` varchar(10) DEFAULT 'USD',
  `currency_rate` decimal(10,2) DEFAULT '1.00',
  `goz` decimal(10,2) DEFAULT '0.00',
  `invoice_date` date NOT NULL,
  `fixing_date` date DEFAULT NULL,
  `fixing_type` varchar(50) DEFAULT 'Standard',
  `previous_balance` decimal(15,2) DEFAULT '0.00',
  `previous_gold` decimal(10,3) DEFAULT '0.000',
  `previous_silver` decimal(10,3) DEFAULT '0.000',
  `total_gross_wt` decimal(10,3) DEFAULT '0.000',
  `total_purity_wt` decimal(10,3) DEFAULT '0.000',
  `subtotal` decimal(15,2) DEFAULT '0.00',
  `additional_amt` decimal(15,2) DEFAULT '0.00',
  `net_total` decimal(15,2) DEFAULT '0.00',
  `discount_amt` decimal(15,2) DEFAULT '0.00',
  `grand_total` decimal(15,2) DEFAULT '0.00',
  `advance_payment` decimal(15,2) DEFAULT '0.00',
  `paid_amt` decimal(15,2) DEFAULT '0.00',
  `balance_amt` decimal(15,2) DEFAULT '0.00',
  `total_amount` decimal(15,2) DEFAULT '0.00',
  `comment` text DEFAULT NULL,
  `status` varchar(20) DEFAULT 'draft',
  `created_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_no` (`invoice_no`),
  KEY `customer_id` (`customer_id`),
  KEY `idx_ref_no` (`ref_no`),
  KEY `invoice_date` (`invoice_date`),
  KEY `fixing_date` (`fixing_date`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create table for Sale Fixing Direct Items
CREATE TABLE IF NOT EXISTS `tbl_sale_fixing_direct_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fixing_id` int(11) NOT NULL,
  `metal_id` int(11) NOT NULL,
  `gross_wt` decimal(10,3) DEFAULT '0.000',
  `purity_wt` decimal(10,3) DEFAULT '0.000',
  `rate` decimal(15,2) DEFAULT '0.00',
  `amount` decimal(15,2) DEFAULT '0.00',
  `purity` decimal(10,2) DEFAULT '1.00',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_fixing_id` (`fixing_id`),
  KEY `idx_metal_id` (`metal_id`),
  CONSTRAINT `fk_fixing_items_fixing` FOREIGN KEY (`fixing_id`) REFERENCES `tbl_sale_fixing_direct` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
