-- Jewellery catalogue header (create/edit from sale order process, etc.)
CREATE TABLE IF NOT EXISTS `tbl_jewelry_catalogue` (
  `id` int NOT NULL AUTO_INCREMENT,
  `metal_id` int DEFAULT NULL,
  `product_id` int DEFAULT NULL,
  `category_id` int DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `short_desc` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `full_desc` mediumtext COLLATE utf8mb4_unicode_ci,
  `barcode` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `design_no` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sku` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `weight` decimal(15,4) DEFAULT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `images_json` mediumtext COLLATE utf8mb4_unicode_ci,
  `bom_json` mediumtext COLLATE utf8mb4_unicode_ci,
  `fill_dmd_gms_rate` tinyint(1) NOT NULL DEFAULT '0',
  `sale_order_id` int DEFAULT NULL,
  `sale_order_item_id` int DEFAULT NULL,
  `repair_order_id` int DEFAULT NULL,
  `repair_order_item_id` int DEFAULT NULL,
  `branch_id` int DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `publish_on_website` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` int DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_jcat_barcode` (`barcode`),
  KEY `idx_jcat_sale_item` (`sale_order_item_id`),
  KEY `idx_jcat_repair_item` (`repair_order_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
