-- Manufacturing closing snapshot (saved from Manufacturing Process → Closing modal)
CREATE TABLE IF NOT EXISTS `tbl_manufacturing_closing` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `department_id` int(11) unsigned NOT NULL,
  `department_user_id` int(11) unsigned NOT NULL,
  `branch_id` int(11) unsigned DEFAULT NULL,
  `closing_date` date NOT NULL,
  `loss_wt` decimal(18,6) DEFAULT NULL,
  `gold_rate` decimal(18,6) DEFAULT NULL,
  `gold_loss_value` decimal(18,6) DEFAULT NULL,
  `purity_per` decimal(18,6) DEFAULT NULL,
  `purity_wt` decimal(18,6) DEFAULT NULL,
  `work_done_kg` decimal(18,6) DEFAULT NULL,
  `avg_loss_per_kg` decimal(18,6) DEFAULT NULL,
  `inward_wt` decimal(18,6) DEFAULT NULL,
  `outward_wt` decimal(18,6) DEFAULT NULL,
  `recovery_wt` decimal(18,6) DEFAULT NULL,
  `closing_wt` decimal(18,6) DEFAULT NULL,
  `production_wt` decimal(18,6) DEFAULT NULL,
  `difference_loss` decimal(18,6) DEFAULT NULL,
  `final_loss` decimal(18,6) DEFAULT NULL,
  `loss_percent` decimal(18,6) DEFAULT NULL,
  `closed_jobs` int(11) unsigned NOT NULL DEFAULT 0,
  `processed_jobs` int(11) unsigned NOT NULL DEFAULT 0,
  `total_jobs` int(11) unsigned NOT NULL DEFAULT 0,
  `metal_weight` decimal(18,6) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `created_by` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_dept_user` (`department_id`,`department_user_id`),
  KEY `idx_closing_date` (`closing_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
