-- Table Structure for tbl_purchase_invoice_items
-- This file contains ALTER TABLE statement to add missing columns
-- Run this statement if you get "Unknown column" errors when saving purchase invoices
-- Note: If you get an error "Duplicate column name", it means the column already exists and you can ignore that error.

-- Single ALTER TABLE statement to add all missing columns
ALTER TABLE `tbl_purchase_invoice_items` 
ADD COLUMN `active` TINYINT(1) DEFAULT 1 COMMENT 'Active status (1=active, 0=inactive)' AFTER `invoice_id`,
ADD COLUMN `rfid` VARCHAR(255) NULL COMMENT 'RFID Code' AFTER `product_characteristic_id`,
ADD COLUMN `voucher_type` VARCHAR(255) NULL COMMENT 'Voucher Type ID' AFTER `rfid`,
ADD COLUMN `huid` VARCHAR(255) NULL COMMENT 'HUID No.' AFTER `design_no`,
ADD COLUMN `category_id` INT(11) NULL COMMENT 'Category ID' AFTER `huid`,
ADD COLUMN `calculation_type` VARCHAR(255) NULL COMMENT 'Calculation Type' AFTER `category_id`,
ADD COLUMN `location_id` INT(11) NULL COMMENT 'Location ID' AFTER `product_name`,
ADD COLUMN `pkt_wt` DECIMAL(10,3) DEFAULT 0.000 COMMENT 'Pkt. Wt.' AFTER `carat`,
ADD COLUMN `pkt_less_wt` DECIMAL(10,3) DEFAULT 0.000 COMMENT 'PKt. Less Wt.' AFTER `pkt_wt`,
ADD COLUMN `requested_purity` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Requested Purity' AFTER `pkt_less_wt`,
ADD COLUMN `requested_wt` DECIMAL(10,3) DEFAULT 0.000 COMMENT 'Requested Wt.' AFTER `requested_purity`,
ADD COLUMN `gold_loss_wt` DECIMAL(10,3) DEFAULT 0.000 COMMENT 'Gold Loss Wt.' AFTER `less_weight`,
ADD COLUMN `gold_loss_value` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Gold Loss Value' AFTER `gold_loss_wt`,
ADD COLUMN `setting_charge` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Setting Charge' AFTER `gold_loss_value`,
ADD COLUMN `wastage_per` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Wastage Per.' AFTER `purity_weight`,
ADD COLUMN `wastage_wt` DECIMAL(10,3) DEFAULT 0.000 COMMENT 'Wastage Wt.' AFTER `wastage_per`,
ADD COLUMN `alloy_wt` DECIMAL(10,3) DEFAULT 0.000 COMMENT 'Alloy Wt.' AFTER `final_weight`,
ADD COLUMN `metal_value` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Metal Value' AFTER `rate`,
ADD COLUMN `metal_cost` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Metal Cost' AFTER `metal_value`,
ADD COLUMN `discount_type` VARCHAR(255) NULL COMMENT 'Discount Type' AFTER `amount`,
ADD COLUMN `discount_per` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Discount Per.' AFTER `discount_type`,
ADD COLUMN `discount_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Discount Amount' AFTER `discount_per`,
ADD COLUMN `discount_type2` VARCHAR(255) NULL COMMENT 'Discount Type 2' AFTER `discount`,
ADD COLUMN `discount_per2` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Discount Per. 2' AFTER `discount_type2`,
ADD COLUMN `discount_amount2` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Discount Amount 2' AFTER `discount_per2`,
ADD COLUMN `discounted_amt` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Discounted Amt.' AFTER `discount_amount2`,
ADD COLUMN `discounted_per` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Discounted Per.' AFTER `discounted_amt`,
ADD COLUMN `making_type` VARCHAR(255) NULL COMMENT 'Making Type' AFTER `discounted_per`,
ADD COLUMN `making_rate` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Making Rate' AFTER `making_type`,
ADD COLUMN `making_discount_amt` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Making Discount Amount' AFTER `making_rate`,
ADD COLUMN `making_actual_value` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Making Actual Value' AFTER `making_amount`,
ADD COLUMN `making_cost` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Making Cost' AFTER `making_actual_value`,
ADD COLUMN `min_price` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Minimum Price' AFTER `making_cost`,
ADD COLUMN `minimum` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Minimum Price Code' AFTER `min_price`,
ADD COLUMN `stone_charge_type` VARCHAR(255) NULL COMMENT 'Stone Charge Type' AFTER `minimum`,
ADD COLUMN `stone_weight` DECIMAL(10,3) DEFAULT 0.000 COMMENT 'Stone Weight' AFTER `stone_charge_type`,
ADD COLUMN `stone_rate` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Stone Rate' AFTER `stone_weight`,
ADD COLUMN `stone_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Stone Amount' AFTER `stone_rate`,
ADD COLUMN `stone_cost` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Stone Cost' AFTER `stone_amount`,
ADD COLUMN `diamond_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Diamond Amount' AFTER `stone_cost`,
ADD COLUMN `purchase_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Purchase Amount' AFTER `diamond_amount`,
ADD COLUMN `sale_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Sale Amount' AFTER `purchase_amount`,
ADD COLUMN `sale_amount_with` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Sale Amount With Tax' AFTER `sale_amount`,
ADD COLUMN `net_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Net Amount' AFTER `sale_amount_with`,
ADD COLUMN `tax` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Tax' AFTER `net_amount`,
ADD COLUMN `other_charge_type` VARCHAR(255) NULL COMMENT 'Other Charge Type' AFTER `tax`,
ADD COLUMN `other_weight` DECIMAL(10,3) DEFAULT 0.000 COMMENT 'Other Weight' AFTER `other_charge_type`,
ADD COLUMN `other_rate` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Other Rate' AFTER `other_weight`,
ADD COLUMN `other_info` VARCHAR(255) NULL COMMENT 'Other Info' AFTER `other_rate`,
ADD COLUMN `other_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Other Amount' AFTER `other_info`,
ADD COLUMN `hallmark_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Hallmark Amount' AFTER `other_amount`,
ADD COLUMN `hallmark_rate` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'HallMark Rate' AFTER `hallmark_amount`,
ADD COLUMN `net_amt_with_tax` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Net Amount With Tax' AFTER `hallmark_rate`,
ADD COLUMN `reverse` DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Reverse' AFTER `net_amt_with_tax`;
